name: madttek
favicon: null
layout_spectrum: 0.24662
typography_spectrum: 0.4415841135196388
title: madt teknology
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0d0f'
    - '#fef9ea'
    - '#cfcaaf'
    - '#a17442'
    - '#546253'
  brandStrength: 0.375
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 0.13829605537466705
purpose: []
